### ISSUE TITLE
Move FoodKeeper files to top level of repository

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/FoodKeeper-API#1]
Instead of having another FoodKeeper-API folder inside the FoodKeeper-API repository, let's move everything up a level.

1. Move the food-pantry folder up to the top level
2. Move .gitignore file up to the top level
3. Move the Food Pantry Data.docx file up to the top level
4. Merge the README contents into the existing top-level README

What do you think? @apham1

**Comment by apham1** [comment]
Sounds good, I'll do that now.

**Comment by apham1** [comment]
Should I close these issues once I've made changes or should I wait for you to review the changes?
