### ISSUE TITLE
Automatically redeploy to Heroku when a pull request is accepted

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/FoodKeeper-API#11]
When a pull request is accepted, the new code needs to be deployed to Heroku.

For example, the pull request for a landing page was accepted and merged, but the changes are not on Heroku (and presumably need to manually moved over.)

**Comment by apham1** [comment]
Currently I think the repository that's being deployed to Heroku isn't the one located in the LibreFoodPantry, because currently the project in LibreFoodPantry doesn't contain files needed to host on Heroku.

**Comment by kwurst** [comment]
Is that because I haven't merged #7 yet? Because I'm hung up on the version number ;-)

**Comment by apham1** [comment]
I think right now it's pointing to Joshua Farrar's repository, I remember him requesting permission to host the one on LibreFoodPantry, not sure where that went though.

**Comment by kwurst** [comment]
Fixed by #14, #13, #7
