### ISSUE TITLE
Use Swagger to generate full API documentation

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/FoodKeeper-API#15]
While the `/` route from Spring is an OK base level of documentation, it would be better to have something with more details (like what is currently in the README.md file.)

Having something like that be autogenerated would be even better. It looks like Swagger might be a solution. https://swagger.io/solutions/api-documentation/

**Comment by kwurst** [comment]
@apham1 Now can you figure out how to have Swagger show example results?

**Comment by kwurst** [comment]
@apham1 Looking at this (https://dzone.com/articles/simplified-spring-swagger?edition=472202&utm_source=Daily%20Digest&utm_medium=email&utm_campaign=Daily%20Digest%202019-04-09) leads me to believe that somehow the model is not set up correctly.
These are all showing models, and our has an empty model.

**Comment by apham1** [comment]
Issue with empty models resolved in Pull Request https://github.com/LibreFoodPantry/FoodKeeper-API/pull/19.
