### ISSUE TITLE
Convert Food Pantry Data.docx to Markdown

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/FoodKeeper-API#2]
@apham1 Did the Food Pantry Data.docx file come from the USDA website? Or did you create it yourself?

If you created it yourself, it would be better to store this in a plain-text file format that can be rendered by GitHub. That would be markdown.

**Comment by apham1** [comment]
The data in the .docx file is included in the README that I added afterwards, so I think it's okay to just delete it.
