### ISSUE TITLE
Endpoint Not Working

### ISSUE THREAD

**Issue by burdged** [LibreFoodPantry/FoodKeeper-API#21]
I had tried to get this endpoint the other day without issue, but am now getting an error.
https://foodkeeper-api.herokuapp.com/products/category/23

The error:
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed May 08 20:30:43 UTC 2019
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by kwurst** [comment]
@burdged Fixed.

**Comment by burdged** [comment]
@kwurst Thanks!
