### ISSUE TITLE
Needs code review and clean-up

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/FoodKeeper-API#4]
I've noticed a number of things that should probably be clean-up before we assign this a non-beta number.

Folder name is one. Package name is another.

I'm sure there are more, but I'll have to take a closer look at it, and post suggestions.

**Comment by kwurst** [comment]
I'm going to suggest the package name be:

`com.github.LibreFoodPantry.FoodKeeper-API`

**Comment by apham1** [comment]
Changed folder name and package name in commit d0a532db53b20a9cb423ccd0a06acf9000d2bdf6.

For the package name, Java doesn't allow packages to have hyphens so I set the package name to:
`com.github.LibreFoodPantry.FoodKeeperAPI`
instead.
