### ISSUE TITLE
Needs a .gitignore file

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/FoodKeeper-API#6]
Files that should not be committed are being committed. For example .bin files.
Investigate .gitignore file contents for Java, Spring, gradle, etc.

**Comment by kwurst** [comment]
And all those files should be deleted in the commit that adds the .gitignore file.

**Comment by apham1** [comment]
e72a385a353105cb2622904d92adc3ecd42cb91c
Updated the .gitignore file to include contents for Eclipse, Java, Gradle, and Spring (using https://www.gitignore.io/).

I followed the instructions here for removing files newly added to the .gitignore: http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/

I believe that this removed all of the files that shouldn't have been committed, let me know if there was something I missed.
